name: Playwright Automation with UK Tor

on:
  schedule:
    - cron: '0 0 1 * *'  # Every day at midnight (UTC)
  workflow_dispatch:   # Allows manual triggering

jobs:
  run-playwright-with-uk-tor:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Tor
      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor

      # Step 2: Configure Tor for UK exit nodes
      - name: Configure Tor for UK exit nodes
        run: |
          echo "ExitNodes {gb}" | sudo tee -a /etc/tor/torrc  # Restrict to UK exit nodes
          echo "ExcludeExitNodes {us},{de},{fr}" | sudo tee -a /etc/tor/torrc  # Exclude non-UK nodes
          echo "StrictNodes 1" | sudo tee -a /etc/tor/torrc  # Ensure it strictly uses UK nodes

      # Step 3: Start Tor Service
      - name: Start Tor Service
        run: |
          sudo service tor start

      # Step 4: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 5: Set up Python (version 3.9 or as needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 6: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      # Step 7: Run the Playwright script that uses Tor with UK exit nodes
      - name: Run Playwright script with UK Tor
        run: |
          python pl10.py
