name: Playwright Automation4

# Schedule the action to run daily at midnight (adjust cron as needed)
on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight (UTC)
  workflow_dispatch:   # Allows manual triggering
      inputs:
        example_input:
          description: 'An example input'
          required: false
          default: 'default_value'

# Specify the jobs to be done
jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository containing the script
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (version 3.9 or as needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas playwright nest_asyncio boxsdk
          playwright install
      # Step 4: Run your Playwright script
      - name: Run Playwright script
        run: |
          python pl2.py
