name: Playwright Automation 10

on:
  schedule:
    - cron: '0 0 1 * *'  # Every day at midnight (UTC)
  workflow_dispatch:   # Allows manual triggering
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default_value'

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Add ProtonVPN repository and install ProtonVPN CLI
      - name: Install ProtonVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://repo.protonvpn.com/debian/public_key.asc | sudo apt-key add -
          echo 'deb https://repo.protonvpn.com/debian stable main' | sudo tee /etc/apt/sources.list.d/protonvpn.list
          sudo apt-get update
          sudo apt-get install -y protonvpn-cli-ng

      # Step 2: Log in and connect to UK VPN (requires credentials)
      - name: Connect to UK VPN
        run: |
          echo "${{ secrets.PROTONVPN_USERNAME }}" | sudo protonvpn-cli login
          sudo protonvpn-cli connect --cc UK

      # Step 3: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Set up Python (version 3.9)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 5: Install Python dependencies and Playwright
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas playwright nest_asyncio google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
          playwright install
          playwright install-deps

      # Step 6: Decode and save JSON file from base64
      - name: Decode and save JSON file
        run: echo "${{ secrets.gar }}" | base64 --decode > file.json

      # Step 7: Run your Playwright script
      - name: Run Playwright script
        run: |
          python pl10.py
